---
title: Michael Spencer
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: sonrisesoftware@gmail.com
description: |
  I'm an iOS, Android, Qt, and web developer. In my spare time I lead the development of Papyros, a Linux- and Qt-based OS using Material Design and other modern features. I also work on various Qt apps and projects.
baseurl: ''
url: http://ibeliever.github.io
twitter_username: iBeliever316
github_username: iBeliever
permalink: "/:year/:month/:title"
markdown: kramdown
post_ext: md
kramdown:
  input: GFM
  syntax_highlighter: rouge
